const logoCards = `
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-01-Falcon-Travel.png" alt="Falcon Travel logo" loading="lazy"></div><div class="editorial-copy"><h3>Falcon Travel</h3><p class="project-type">Travel &amp; Tourism</p><h4>Concept</h4><p>A dynamic falcon symbol turns flight into a clear visual cue for movement, freedom and travel.</p><h4>Color Psychology</h4><p>Blue builds trust and reliability, while turquoise adds freshness, energy and exploration.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-02-Arksta-Misr.png" alt="Arksta Misr logo" loading="lazy"></div><div class="editorial-copy"><h3>Arksta Misr</h3><p class="project-type">Real Estate Development</p><h4>Concept</h4><p>A modular architectural mark uses repeated rising forms to suggest buildings, development, structure and long-term growth.</p><h4>Color Psychology</h4><p>Navy conveys trust and stability; muted gold adds value, prestige and a premium real-estate character.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-03-Sawani.png" alt="Sawani restaurant logo" loading="lazy"></div><div class="editorial-copy"><h3>Sawani</h3><p class="project-type">Restaurant</p><h4>Concept</h4><p>Decorative Arabic calligraphy and a circular composition create a warm identity rooted in oriental dining and hospitality.</p><h4>Color Psychology</h4><p>Warm brown conveys tradition and authenticity, while gold adds warmth, quality and a refined dining character.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-04-Teamim.png" alt="Teamim logo" loading="lazy"></div><div class="editorial-copy"><h3>Teamim</h3><p class="project-type">Software &amp; Technology</p><h4>Concept</h4><p>Connected geometric forms create an abstract tech mark that suggests integration, systems and software solutions.</p><h4>Color Psychology</h4><p>Purple signals innovation, creativity and a distinctive technology-led personality.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-05-Space-Burger.png" alt="Space Burger logo" loading="lazy"></div><div class="editorial-copy"><h3>Space Burger</h3><p class="project-type">Burger Restaurant</p><h4>Concept</h4><p>An astronaut mascot combined with bold lettering builds a playful food identity with a memorable space-themed concept.</p><h4>Color Psychology</h4><p>Purple evokes imagination and creativity; light blue adds youthful energy and a friendly tone.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-06-Nateast.png" alt="Nateast logo" loading="lazy"></div><div class="editorial-copy"><h3>Nateast</h3><p class="project-type">Natural Food Products</p><h4>Concept</h4><p>A refined serif wordmark integrates a wheat motif, linking the identity directly to natural ingredients and farm-to-package quality.</p><h4>Color Psychology</h4><p>Deep blue communicates trust and quality; wheat gold reflects nature, harvest, warmth and premium ingredients.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-07-Vital.png" alt="Vital logo" loading="lazy"></div><div class="editorial-copy"><h3>Vital</h3><p class="project-type">Insect Trap Brand</p><h4>Concept</h4><p>A refined wordmark creates a clean, dependable identity suited to modern insect-control products.</p><h4>Color Psychology</h4><p>Navy communicates trust and reliability; gold adds quality, value and distinction.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-08-Samer-Rose.png" alt="Samer Rose logo" loading="lazy"></div><div class="editorial-copy"><h3>Samer Rose</h3><p class="project-type">Chocolate Shop</p><h4>Concept</h4><p>An organic monogram paired with a clean wordmark creates a warm, crafted identity for a chocolate brand.</p><h4>Color Psychology</h4><p>Brown naturally evokes chocolate and warmth; beige adds softness, refinement and a premium feel.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-09-Ali-Kassab.png" alt="Ali Kassab logo" loading="lazy"></div><div class="editorial-copy"><h3>Ali Kassab</h3><p class="project-type">Contracting &amp; Construction</p><h4>Concept</h4><p>A geometric monogram uses strong angular forms to express structure, construction, stability and forward progress.</p><h4>Color Psychology</h4><p>Deep blue conveys stability and trust; cyan adds a modern, progressive character.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-10-Jero-Cafe.png" alt="Jero Cafe logo" loading="lazy"></div><div class="editorial-copy"><h3>Jero Cafe</h3><p class="project-type">Cafe</p><h4>Concept</h4><p>Expressive Arabic calligraphy creates a bold, culturally rooted identity, while the smaller cafe descriptor keeps the category clear.</p><h4>Color Psychology</h4><p>Deep navy adds confidence and heritage; bright cyan brings freshness, energy and a contemporary cafe feel.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-11-Dima-Gold.png" alt="Dima Gold logo" loading="lazy"></div><div class="editorial-copy"><h3>Dima Gold</h3><p class="project-type">Gold &amp; Jewelry</p><h4>Concept</h4><p>An ornamental emblem centered on the letter D gives the brand a crafted, classic jewelry character.</p><h4>Color Psychology</h4><p>Gold represents luxury and value; brown introduces heritage, warmth and sophistication.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-12-Salam-Tourism.png" alt="Salam Tourism logo" loading="lazy"></div><div class="editorial-copy"><h3>Salam Tourism</h3><p class="project-type">Travel &amp; Tourism</p><h4>Concept</h4><p>A circular, flowing mark suggests routes, continuity and movement, paired with a clear bilingual wordmark.</p><h4>Color Psychology</h4><p>Black gives the identity confidence, clarity and a professional, timeless presence.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-13-Qatra.png" alt="Qatra logo" loading="lazy"></div><div class="editorial-copy"><h3>Qatra</h3><p class="project-type">Water Filtration</p><h4>Concept</h4><p>Arabic lettering integrates water and natural forms to communicate purification and cleaner everyday water.</p><h4>Color Psychology</h4><p>Blue represents purity and trust; green reinforces health, freshness and nature.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-14-Glow-And-Care.png" alt="Glow and Care logo" loading="lazy"></div><div class="editorial-copy"><h3>Glow &amp; Care</h3><p class="project-type">Natural Massage Candles</p><h4>Concept</h4><p>Protective hands frame a glowing drop, visually linking natural candle warmth with body-care and skin-care benefits.</p><h4>Color Psychology</h4><p>Black adds elegance and strength; gold communicates warmth, glow, care and product quality.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-15-Al-Derwaza.png" alt="Al Derwaza logo" loading="lazy"></div><div class="editorial-copy"><h3>Al Derwaza</h3><p class="project-type">Marketing &amp; Sports Investment</p><h4>Concept</h4><p>A corporate wordmark and shield-based sports symbol balance business credibility with a clear athletic association.</p><h4>Color Psychology</h4><p>Burgundy conveys strength and authority; grey supports balance, seriousness and professionalism.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-16-El-Fareej-Bakery.png" alt="El Fareej Bakery logo" loading="lazy"></div><div class="editorial-copy"><h3>El Fareej Bakery</h3><p class="project-type">Bakery</p><h4>Concept</h4><p>A compact Arabic badge creates a recognizable neighborhood bakery identity with a strong traditional and hand crafted feel.</p><h4>Color Psychology</h4><p>Blue suggests trust and cleanliness; gold supports quality, warmth and traditional character.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-17-Mathaf.png" alt="Mathaf logo" loading="lazy"></div><div class="editorial-copy"><h3>Mathaf</h3><p class="project-type">Bazaar &amp; Gallery</p><h4>Concept</h4><p>Geometric Arabic lettering draws on decorative heritage to create a distinctive identity with an artisanal character.</p><h4>Color Psychology</h4><p>Brown suggests authenticity and heritage; gold reinforces craftsmanship, value and elegance.</p></div></article>
<article class="work-card editorial-card logo-card"><div class="logo-visual"><img src="assets/logos/Marco.Sawiris-Logo-Design-18-Karam-El-Shami.png" alt="Karam El Shami logo" loading="lazy"></div><div class="editorial-copy"><h3>Karam El Shami</h3><p class="project-type">Bakery</p><h4>Concept</h4><p>A character-led emblem with Arabic detailing gives the bakery a friendly identity inspired by Levantine craft and fresh baking.</p><h4>Color Psychology</h4><p>Warm brown tones evoke baked goods and comfort; gold reinforces quality and heritage.</p></div></article>
`;

const portfolioGrid = document.getElementById('portfolio-grid');
portfolioGrid?.insertAdjacentHTML('beforeend', logoCards);
portfolioGrid?.querySelectorAll('.logo-card').forEach(card => {
  card.dataset.category = 'logo';
  card.classList.add('is-hidden', 'is-visible');
});

const workTitle = document.getElementById('work-title');
const workDescription = document.getElementById('work-description');
document.querySelectorAll('.filter').forEach(button => button.addEventListener('click', () => {
  const filter = button.dataset.filter;
  document.querySelectorAll('#portfolio-grid .work-card').forEach(card => {
    card.classList.toggle('is-hidden', card.dataset.category !== filter);
  });
  if (filter === 'logo') {
    if (workTitle) workTitle.textContent = 'Logo Design.';
    if (workDescription) workDescription.textContent = 'A selected collection of brand marks developed around clear ideas, relevant symbolism and purposeful color systems.';
  } else {
    if (workTitle) workTitle.textContent = 'Editorial Design.';
    if (workDescription) workDescription.textContent = 'A curated selection of editorial design, company profiles, catalogs, magazines and production-ready print work.';
  }
}));
