document.documentElement.classList.add('motion-ready');
const reduceMotion = matchMedia('(prefers-reduced-motion: reduce)').matches;
const items = [...document.querySelectorAll('.section-head,.work-card,.about-grid > *,.stat,.role,.contact > *,.skill,.showreel-frame')];
items.forEach((item,index)=>{item.classList.add('reveal');item.classList.add(item.classList.contains('work-card')||item.classList.contains('showreel-frame')?'reveal-project':index%2?'reveal-right':'reveal-left');item.style.setProperty('--reveal-delay',Math.min(index%5,4)*90+'ms')});
if(!reduceMotion){
 const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -8% 0px'});items.forEach(item=>observer.observe(item));
 const countObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const el=entry.target,match=el.textContent.trim().match(/^(\d+)(.*)$/);if(!match)return;const target=+match[1],suffix=match[2],start=performance.now();function tick(now){const p=Math.min((now-start)/1100,1),e=1-Math.pow(1-p,3);el.textContent=Math.round(target*e)+suffix;if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick);countObserver.unobserve(el)}),{threshold:.6});document.querySelectorAll('.stat strong').forEach(el=>countObserver.observe(el));
 let ticking=false;function scrollMotion(){const portrait=document.querySelector('.portrait:not(.hero-video)');if(portrait)portrait.style.transform='scale(1.08) translate3d(0,'+Math.min(scrollY*.065,42)+'px,0)';document.querySelectorAll('.project').forEach(card=>{const rect=card.getBoundingClientRect();if(rect.bottom<0||rect.top>innerHeight)return;const p=(innerHeight-rect.top)/(innerHeight+rect.height),img=card.querySelector('img');if(img)img.style.transform='scale(1.08) translate3d(0,'+((p-.5)*24)+'px,0)'});ticking=false}addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(scrollMotion);ticking=true}},{passive:true});scrollMotion();
}else items.forEach(item=>item.classList.add('is-visible'));
const filters=[...document.querySelectorAll('.filter')],cards=[...document.querySelectorAll('.work-card')];filters.forEach(button=>button.addEventListener('click',()=>{filters.forEach(item=>item.classList.remove('is-active'));button.classList.add('is-active');const filter=button.dataset.filter;cards.forEach((card,index)=>{const visible=filter==='all'||card.dataset.category===filter;card.classList.toggle('is-hidden',!visible);if(visible){card.animate([{opacity:0,transform:'translateY(24px) scale(.97)'},{opacity:1,transform:'none'}],{duration:480,delay:Math.min(index%8,7)*45,easing:'cubic-bezier(.16,1,.3,1)'})}})}));
if(!reduceMotion){const sectionObserver=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle('section-active',entry.isIntersecting)),{threshold:.18});document.querySelectorAll('main section').forEach(section=>sectionObserver.observe(section));}
